# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: abc.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'abc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tabc.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x01\n\nRobotState\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08position\x18\x02 \x03(\x01\x12\x10\n\x08velocity\x18\x03 \x03(\x01\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x04 \x03(\x01\x12\x0e\n\x06torque\x18\x05 \x03(\x01\x12\x0c\n\x04pose\x18\x06 \x03(\x01\"\x87\x01\n\x0cGripperState\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08position\x18\x02 \x03(\x01\x12\x10\n\x08velocity\x18\x03 \x03(\x01\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x04 \x03(\x01\x12\x0e\n\x06torque\x18\x05 \x03(\x01\"K\n\x0cInstructions\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"I\n\nAnnotation\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'abc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTSTATE']._serialized_start=47
  _globals['_ROBOTSTATE']._serialized_end=194
  _globals['_GRIPPERSTATE']._serialized_start=197
  _globals['_GRIPPERSTATE']._serialized_end=332
  _globals['_INSTRUCTIONS']._serialized_start=334
  _globals['_INSTRUCTIONS']._serialized_end=409
  _globals['_ANNOTATION']._serialized_start=411
  _globals['_ANNOTATION']._serialized_end=484
# @@protoc_insertion_point(module_scope)
